language: php

sudo: required

notifications:
  email: false

addons:
  postgresql: "9.4"
  firefox: "47.0.1"
  #chrome: stable
  apt:
    packages:
      # can be omitted because mustache is not in use
      # - oracle-java8-installer
      # - oracle-java8-set-default
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

# PHP Compatibility Matrix Moodle
# Moodle 3.1: php5.4, php5.5, php5.6, php7.0 (lim)
# Moodle 3.2: php5.6, php7.0 (lim), php7.1 (lim)
# Moodle 3.3: php5.6, php7.0 (lim), php7.1 (lim)
# Moodle 3.4: php7.0, php7.1, php7.2 (exp)
# Moodle 3.5: php7.0, php7.1, php7.2 (exp)
# Moodle 3.6: php7.0, php7.1, php7.2 (exp), php7.3 (dev)
# lim: limited, exp: expected, dev: non-production
php:
 - 7.0
 - 7.1
 - 7.2

env:
  - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql

matrix:
  include:
    # Some MySQL as backend with various PHP versions, but just some to save matrix slots
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli

before_install:
  # php settings
  - echo "upload_max_filesize=20M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "post_max_size=20M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # moodle-plugin-ci installation (https://github.com/blackboard-open-source/moodle-plugin-ci/blob/master/.travis.dist.yml)
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  # chromedriver
  #- chromedriverversion=$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE);
  #- curl https://chromedriver.storage.googleapis.com/$chromedriverversion/chromedriver_linux64.zip | gunzip - > ci/bin/chromedriver
  #- chmod +x ci/bin/chromedriver

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  #- moodle-plugin-ci mustache #currently no mustache relevant files, so we can also omit the java packages above
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat --profile chrome
  - moodle-plugin-ci behat # with firefox
