language: php

sudo: required

notifications:
  email: false

addons:
  postgresql: "9.4"
  firefox: "47.0.1"
  #chrome: stable
  apt:
    packages:
       # can be omitted because mustache is not in use
  #    - oracle-java8-installer
  #    - oracle-java8-set-default
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

# PHP Compatibility Matrix Moodle
# Moodle 3.1: php5.4, php5.5, php5.6, php7.0 (lim)
# Moodle 3.2: php5.6, php7.0 (lim), php7.1 (lim)
# Moodle 3.3: php5.6, php7.0 (lim), php7.1 (lim)
# Moodle 3.4: php7.0, php7.1, php7.2 (exp)
# lim: limited, exp: expected
php:
 - 7.0
 - 7.1
 - 7.2

env:
  - MOODLE_BRANCH=MOODLE_34_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_35_STABLE DB=pgsql
  - MOODLE_BRANCH=MOODLE_36_STABLE DB=pgsql

matrix:
  include:
    # Some MySQL as backend with various PHP versions, but just some to save matrix slots
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_34_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_35_STABLE DB=mysqli
    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli

before_install:
  - if [ $MOODLE_BRANCH == 'MOODLE_31_STABLE' ]; then MPCIV=1; else MPCIV=2; fi
  # php settings
  - phpenv config-rm xdebug.ini
  - echo "upload_max_filesize=20M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "post_max_size=20M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # moodle dependencies
  - if [ $MPCIV == '2' ]; then nvm install 8.9; nvm use 8.9; fi
  # moodle-plugin-ci installation
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^$MPCIV
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  # chromedriver
  #- chromedriverversion=$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE);
  #- curl https://chromedriver.storage.googleapis.com/$chromedriverversion/chromedriver_linux64.zip | gunzip - > ci/bin/chromedriver
  #- chmod +x ci/bin/chromedriver

install:
  - moodle-plugin-ci install
  # change firefox to chrome for older moodles
  #- if [ $MPCIV == '1' ]; then sed -i 's/firefox/chrome/' moodle/config.php; fi
  #- if [ $MPCIV == '1' ]; then curl https://raw.githubusercontent.com/blackboard-open-source/moodle-plugin-ci/2.1.1/src/Command/BehatCommand.php > ci/src/Command/BehatCommand.php ; fi
  #- if [ $MPCIV == '1' ]; then moodle-plugin-ci add-config '$CFG->behat_profiles = ["default" => ["browser" => "firefox", "wd_host" => "http://localhost:4444/wd/hub",], "chrome" => ["browser" => "chrome", "wd_host" => "http://localhost:4444/wd/hub",],];'; fi
  #- if [ $MPCIV == '1' ]; then moodle-plugin-ci add-config '$CFG->behat_profiles = ["default" => ["browser" => "chrome", "wd_host" => "http://localhost:4444/wd/hub",],];'; fi
  #- cat moodle/config.php

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - if [ $MPCIV == '2' ]; then moodle-plugin-ci validate; fi
  - if [ $MPCIV == '2' ]; then moodle-plugin-ci savepoints; fi
  #- if [ $MPCIV == '2' ]; then moodle-plugin-ci; fi mustache #currently no mustache relevant files, so we can also save the oracle packages
  - if [ $MPCIV == '2' ]; then moodle-plugin-ci grunt; fi
  - if [ $MPCIV == '1' ]; then moodle-plugin-ci csslint; fi
  - if [ $MPCIV == '1' ]; then moodle-plugin-ci shifter; fi
  - if [ $MPCIV == '1' ]; then moodle-plugin-ci jshint; fi
  - if [ $MPCIV == '2' ]; then moodle-plugin-ci phpunit --coverage-text; fi # output code coverage in MPCIV 2
  - if [ $MPCIV == '1' ]; then moodle-plugin-ci phpunit; fi
  - if [ $MPCIV == '2' ]; then moodle-plugin-ci behat --profile chrome; fi
  #TODO: Swap between firefox and chrome using environment info
  #- if [ $MPCIV == '2' ]; then moodle-plugin-ci behat; fi # is profile firefox
  - if [ $MPCIV == '1' ]; then moodle-plugin-ci behat || true; fi # currently not working at all
  #- java -jar moodle/selenium.jar &
  #- if [ $MPCIV == '1' ]; then php moodle/vendor/bin/behat --config $(pwd)/moodledata/behat_moodledata/behatrun/behat/behat.yml; fi
