# https://moodlerooms.github.io/moodle-plugin-ci/TravisFileExplained.html

language: php

sudo: false

addons:
  firefox: "47.0.1"
  postgresql: "9.3"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  # - 5.6
  # - 7.0
  - 7.1

env:
  global:
    # - MOODLE_BRANCH=MOODLE_31_STABLE
    # - MOODLE_BRANCH=MOODLE_32_STABLE
    - MOODLE_BRANCH=MOODLE_33_STABLE
  matrix:
    # - DB=pgsql
    - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  # PHP Copy/Paste Detector.
  # Detects some duplicated code in api.php. Disabling test until ready to refactor.
  # - moodle-plugin-ci phpcpd
  # PHP Mess Detector
  # Detects a noisy number of violations, but leaving active to pickup errors.
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
